### ISSUE TITLE
pke.unsupervised.PositionRank() load_document max_length exectption

### ISSUE THREAD

**Issue by hafidmermouri** [boudinfl/pke#172] opened 2021-09-28 19:59 UTC
Hello
I'm facing this issue on a production server Ubuntu 18
`load() got an unexpected keyword argument 'max_length'`
It's working just fine on my mac, here is the line causing the issue :
`extractor.load_document(input = text, language = self.lang, normalization = 'lemmatization')`
this is for English language. i've tried to pass a `max_length = 10000000` params but didn't help.
Any idea how to fix it? Thanks

**Comment by ygorg** [comment] 2021-09-28 21:47
Hi, this might have been fixed in [this commit](https://github.com/boudinfl/pke/commit/37d980704954e3ffb84c587e2b97af8dbb8e59aa).
Please try installing the latest version of `pke`.

If it does not solve your problem please paste the output of `python3 -m spacy validate`, and a minimal *reproducible* code that triggers the error you face.

**Comment by hafidmermouri** [comment] 2021-09-28 22:20
I've tried `pip3 install -U git+https://github.com/boudinfl/pke.git` but still get the error.
here is the result of `validate` :
`
✔ Loaded compatibility table

================= Installed pipeline packages (spaCy v3.1.3) =================
ℹ spaCy installation:
/home/hafid/.local/lib/python3.6/site-packages/spacy

NAME              SPACY            VERSION                            
fr_core_news_sm   >=3.1.0,<3.2.0   3.1.0   ✔
en_core_web_sm    >=3.1.0,<3.2.0   2.2.0   ✔
`

**Comment by hafidmermouri** [comment] 2021-09-29 07:18
@ygorg  spacy version is the same on my mac and it's working. the only difference I can see is the version of the `en_core_web_sm` which is 3.1.2 on my mac and 2.2.0 on my Ubuntu server

````
NAME              SPACY            VERSION                            
it_core_news_sm   >=3.1.0,<3.2.0   3.1.0   ✔
es_core_news_sm   >=3.1.0,<3.2.0   3.1.0   ✔
en_core_web_sm    >=3.1.0,<3.2.0   3.1.0   ✔
fr_core_news_sm   >=3.1.0,<3.2.0   3.1.0   ✔
de_core_news_sm   >=3.1.0,<3.2.0   3.1.0   ✔
```
thanks for the help

**Comment by ygorg** [comment] 2021-09-29 12:13
Hi, since spacy v3 the `max_length` parameter was removed. So it should not be used (see [here](https://github.com/boudinfl/pke/blob/485c93879988f5b0290d241ad484c4fae7454530/pke/readers.py#L158)).

This parameter is here only for supporting spacy v2.

**Comment by hafidmermouri** [comment] 2021-09-29 12:16
thanks @ygorg but I'm not using it actually. I got the error but don't know what's going on underground.
do you know how I can update en_core_web_sm to 3.2.0? or anything I could try to remove this error?

**Comment by ygorg** [comment] 2021-09-29 12:35
Ah yes, to update the spacy model you can do `python3 -m spacy download en_core_web_sm`.

**Comment by hafidmermouri** [comment] 2021-09-29 13:15
@ygorg I already did this but looks like the last version available for python 3.6 is the 2.2.0...

**Comment by ygorg** [comment] 2021-09-30 08:42
On my ubuntu machine with pyhon3.6 i was able to install spacy version 3.1.3 (but I needed to remove all the installed models beforehand).
Alternatively you can reinstall the version 2 of spacy using  `pip install "spacy<3"`

**Comment by hafidmermouri** [comment] 2021-09-30 11:57
thanks @ygorg ! Updating python to 3.9 made it finally.

**Comment by ygorg** [comment] 2021-09-30 16:09
Glad to hear ! Sorry for the inconvenience of the `max_length parameter`.

**Closed by ygorg** 2021-09-30 16:09 UTC
